### ISSUE TITLE
Petalinux-build failing after importing .xsa

### ISSUE THREAD

**Issue by mjkpolo** [Digilent/Zybo-Z7#10]
*First of all I apologize for misunderstandings I am a student trying to learn If I did this incorrectly I will remove the issue ASAP*

I made this simple design to practice using AXI based on [this guide](https://www.hackster.io/whitney-knitter/introduction-to-using-axi-dma-in-embedded-linux-5264ec):
<img width="1093" alt="Screen Shot 2022-09-02 at 1 28 33 PM" src="https://user-images.githubusercontent.com/70489411/188215752-e70128e0-1d88-45e0-8c05-eef621c43e51.png">

Next, I create a Petalinux project with the BSP:
```bash
petalinux-create -t project -s Zybo-Z7-20-Petalinux-2021-1.bsp
```

running `petalinux-build -c rootfs` works

However, if I import the xsa file of that board design:
```bash
petalinux-config --get-hw-description=design_1_wrapper.xsa
```
running `petalinux-build -c rootfs` has the following error:
[build.log](https://github.com/Digilent/Zybo-Z7/files/9480294/build.log)

Then I get a different error if I create a dma app first:

```bash
petalinux-create -t apps --template c --name dmatest --enable
```
running `petalinux-build -c rootfs` has the following error (not adding anything to the dmatest.c): 
[build.log](https://github.com/Digilent/Zybo-Z7/files/9480335/build.log)

Am I doing this incorrectly? I tried doing this with the Zynq zc706 bsp and Xilinx board design and it seemed to compile so I'm assuming it's an issue with this BSP.

Thank you!!! I appreciate the patience and help

**Comment by astrosloth-stc** [comment]
I'm having a similar issue. I downloaded what seems like it should be the FPGA project: [Zybo-Z7-20-Pcam-5C-hw.xpr.zip](https://github.com/Digilent/Zybo-Z7/releases/download/20%2FPcam-5C%2F2021.1-1/Zybo-Z7-20-Pcam-5C-hw.xpr.zip)

and if I build, export the xsa, and try to import into petalinux, i'm not able to complete petalinux-build.

Is there a different FPGA project I should be starting from?

**Comment by mjkpolo** [comment]
> I'm having a similar issue. I downloaded what seems like it should be the FPGA project: [Zybo-Z7-20-Pcam-5C-hw.xpr.zip](https://github.com/Digilent/Zybo-Z7/releases/download/20%2FPcam-5C%2F2021.1-1/Zybo-Z7-20-Pcam-5C-hw.xpr.zip)
> 
> and if I build, export the xsa, and try to import into petalinux, i'm not able to complete petalinux-build.
> 
> Is there a different FPGA project I should be starting from?

I don’t think you use petalinux for that, I think you just use vivado/vitis or at least that’s what I did to get it running
